baseURL = "/"
languageCode = "en-us"
title = "Kappa Eta Kappa"

[params]
description = "Kappa Eta Kappa is a national, professional co-ed Electrical Engineering Fraternity founded 1923. Delta Chapter is located at the University of Wisconsin, Madison."
twitter_username = "khkDelta"
github_username = "kappaetakappa"
President = "Nicole Kemnitz"
Vice_President = "Krishnang Patra"
Treasurer = "Raghav Jindal"
Secretary = "Katarina Bauer"
Publicity_Chair = "Sheridan Zimmerman"
Pledge_Trainer = "Hunter Lawry"
House_Steward = "Tanner Birenbaum"
Social_Chair = "Karan Kapur"

[permalinks]
posts = "/posts/:year-:month-:day-:title/"

[blackfriday]
hrefTargetBlank = true

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1
[[menu.main]]
name = "About"
pageRef = "/posts/"
weight = 2
[[menu.main]]
name = "Events"
pageRef = "/events/"
weight = 3
[[menu.main]]
name = "Members"
pageRef = "/members/"
weight = 4
[[menu.main]]
name = "Organizations"
identifier = "organizations"
weight = 5
[[menu.main]]
name = "Delta Alumni Association"
url = "http://daa.khk.org"
parent = "organizations"
weight = 1
[[menu.main]]
name = "National Association"
url = "http://khk.org"
parent = "organizations"
weight = 2
[[menu.main]]
name = "National Executive Council"
url = "http://khk.org/contact"
parent = "organizations"
weight = 3
[[menu.main]]
name = "Other Chapters"
identifier = "other-chapters"
parent = "organizations"
weight = 4
[[menu.main]]
name = "Beta (UM - St Paul/Twin Cities)"
url = "http://khkbeta.org"
parent = "other-chapters"
weight = 1
[[menu.main]]
name = "Iota (UM - St Cloud)"
url = "http://iota.khk.org"
parent = "other-chapters"
weight = 2
